"""
Alerts API endpoints
"""
from flask import Blueprint, jsonify
from backend.database.db import db
from datetime import datetime
import random

alert_bp = Blueprint('alerts', __name__)

@alert_bp.route('', methods=['GET'])
def get_alerts():
    """Get active trading alerts."""
    try:
        # In a real system, these would be generated by the Strategy Engine
        # For now, we'll generate them based on real market movers if available
        
        alerts = []
        
        # Get top gainers/losers to generate alerts
        # We can reuse the logic from movers_routes or just query DB directly
        # For simplicity, let's query the latest market data for a few active stocks
        
        # Sample stocks to check (mix of NIFTY 50)
        sample_stocks = ['RELIANCE', 'HDFCBANK', 'INFY', 'TCS', 'ICICIBANK', 'SBIN', 'TATAMOTORS']
        
        for symbol in sample_stocks:
            data = db.get_latest_market_data(symbol)
            if data:
                change_percent = ((data['close'] - data['open']) / data['open']) * 100
                
                # Generate BUY alert if strong positive momentum
                if change_percent > 1.5:
                    alerts.append({
                        'id': f"alert_{symbol}_{int(datetime.now().timestamp())}",
                        'instrument': f"{symbol} {data['close']:.0f} CE", # Simulated Option
                        'type': 'BUY',
                        'confidence': 80 + int(change_percent * 2), # Higher change = higher confidence
                        'reason': f"Strong bullish momentum ({change_percent:.2f}%), volume spike detected.",
                        'timestamp': datetime.now().strftime('%I:%M %p'),
                        'strikePrice': round(data['close'], -1), # Round to nearest 10
                        'targetPrice': round(data['close'] * 1.02, 1),
                        'stopLoss': round(data['close'] * 0.99, 1)
                    })
                
                # Generate SELL alert if strong negative momentum
                elif change_percent < -1.5:
                    alerts.append({
                        'id': f"alert_{symbol}_{int(datetime.now().timestamp())}",
                        'instrument': f"{symbol} {data['close']:.0f} PE", # Simulated Option
                        'type': 'BUY', # Buying PE is bearish
                        'confidence': 80 + int(abs(change_percent) * 2),
                        'reason': f"Breakdown below support ({change_percent:.2f}%), bearish divergence.",
                        'timestamp': datetime.now().strftime('%I:%M %p'),
                        'strikePrice': round(data['close'], -1),
                        'targetPrice': round(data['close'] * 0.98, 1),
                        'stopLoss': round(data['close'] * 1.01, 1)
                    })

        # If no real alerts generated (e.g. market closed/flat), add some sample ones based on real prices
        if not alerts:
            # Fallback to some static-ish alerts but with current timestamps
            alerts = [
                {
                    'id': '1',
                    'instrument': 'NIFTY 24500 CE',
                    'type': 'BUY',
                    'confidence': 85,
                    'reason': 'Strong bullish momentum, RSI above 70.',
                    'timestamp': datetime.now().strftime('%I:%M %p'),
                    'strikePrice': 120.50,
                    'targetPrice': 150.00,
                    'stopLoss': 105.00
                },
                {
                    'id': '2',
                    'instrument': 'BANKNIFTY 52200 PE',
                    'type': 'BUY',
                    'confidence': 78,
                    'reason': 'Breaking key support level, high volume.',
                    'timestamp': datetime.now().strftime('%I:%M %p'),
                    'strikePrice': 210.00,
                    'targetPrice': 280.00,
                    'stopLoss': 180.00
                }
            ]
            
        return jsonify(alerts), 200
        
    except Exception as e:
        print(f"Error fetching alerts: {e}")
        return jsonify([]), 500
